#!/bin/sh

. /lib/functions.sh

reset_enable=$(uci get acn.settings.reset_btn_enable)

[ "$reset_enable" -eq 0 ] && {
        logger "$BUTTON button is disabled"
        echo "$BUTTON button is disabled" > /dev/console
        exit 0
}

OVERLAY="$( grep ' /overlay ' /proc/mounts )"

case "$ACTION" in
pressed)
	[ -z "$OVERLAY" ] && return 0

	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ "$SEEN" -lt 1 ]
	then
		echo "REBOOT" > /dev/console
		sync
		reboot
	elif [ "$SEEN" -ge 5 -a -n "$OVERLAY" ]
	then
		echo "FACTORY RESET" > /dev/console
		jffs2reset -y && reboot &
	fi
;;
esac

return 0
