#!/bin/sh /etc/rc.common

START=19

USE_PROCD=1
PROG=/usr/sbin/ec-fp

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 1 0
	procd_close_instance
}

reload_service() {
	restart
}
