#!/bin/sh /etc/rc.common

START=99
STOP=16

USE_PROCD=1
PROG="/usr/bin/mac_authd"

start_service() {
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn
	procd_close_instance
	#mac_authd >/dev/null 2>&1 &
}

stop_service() {
	killall -9 mac_authd
}

reload_service() {
	stop
	start
}

