#!/bin/sh /etc/rc.common

START=98
USE_PROCD=1
QOSSRV=/sbin/QosUserSrv
MAX_RF_NO=2

start_service() {
	procd_open_instance
	capwap=$(uci get acn.capwap.state)
	if [ -x "${QOSSRV}" ] && [ "${capwap}" = "1" ]; then
		procd_set_param command ${QOSSRV} $MAX_RF_NO
	fi
	procd_close_instance
}

stop_service() {
	pid=$(ps |grep QosUserSrv | grep -v grep | awk '{print $1}')
	[ -n "${pid}" ] && kill $pid
}

service_triggers() {
    procd_add_reload_trigger acn
}
