#!/bin/sh /etc/rc.common

START=92

boot() {
	local tip_mode=$(uci -q get acn.mgmt.management)
	[ ! -z $tip_mode ] && [ "$tip_mode" -eq 3 ] && {
		/sbin/send_clientinfo_period.sh stop
		return 0
	}

	/sbin/send_clientinfo_period.sh boot

}
