#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

USE_PROCD=1
PROG=/usr/sbin/telnetd

validate_telnetd_section() {
	uci_validate_section telnetd telnetd "${1}" \
		'enable:bool' 'Port:uinteger'
}

check_enable() {
	config_get telnetd_enabled $1 enable
	config_get telnetd_port $1 Port
}

start_service() {
	local telnetd_enabled
	local telnetd_port
	config_load telnetd
	config_foreach check_enable telnetd

	validate_telnetd_section telnetd || {
		echo "validation failed"
		return 1
	}

	[ $telnetd_enabled = 0 ] && return 0

	[ -z "$telnetd_port" ] && {
		telnetd_port=23
	}

	validate_telnetd_section	
	procd_open_instance
	procd_set_param command "$PROG" -F -p "$telnetd_port" -l /usr/libexec/login.sh
	procd_set_param respawn
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "telnetd"
	procd_add_validation validate_telnetd_section
}
