#!/bin/sh

http_pt=$(uci -q get uhttpd.main.listen_http|awk '{print $1}'|awk -F ':' '{print $2}')
https_pt=$(uci -q get uhttpd.main.listen_https|awk '{print $1}'|awk -F ':' '{print $2}')

if [ "$http_pt" != "" ]; then
	uci del uhttpd.main.listen_http
	uci add_list uhttpd.main.listen_http=$http_pt
	uci commit uhttpd
fi

if [ "$https_pt" != "" ]; then
	uci del uhttpd.main.listen_https
	uci add_list uhttpd.main.listen_https=$https_pt
	uci commit uhttpd
fi

exit 0

