#!/bin/sh

#wireless config
if [ "$(uci get wireless.wmesh)" == "" ]; then
  uci set wireless.wmesh='wifi-iface'
  uci set wireless.wmesh.ifname='mesh0'
  uci set wireless.wmesh.network='bat0_hardif_mesh0'
  uci set wireless.wmesh.mode='mesh'
  uci set wireless.wmesh.mesh_fwding='0'
  uci set wireless.wmesh.mcast_rate='24000'
  uci set wireless.wmesh.key='12345678'
  uci set wireless.wmesh.encryption='none'
  uci set wireless.wmesh.device='nil'
  uci set wireless.wmesh.disabled='1'
  uci set wireless.wmesh.mesh_id='openmesh'
  uci set wireless.wmesh.network_behavior='nil'
  uci set wireless.wmesh.network_name='nil'
  uci set wireless.wmesh.signal_connect='-128'
  uci set wireless.wmesh.signal_stay='-128'
  uci commmit wireless.wmesh
fi

#network config
uci del network.bat0
uci set network.bat0='interface'
uci set network.bat0.proto='batadv'
uci set network.bat0.routing_algo='BATMAN_IV'
uci set network.bat0.orig_interval='5000'
uci set network.bat0.distributed_arp_table='0'
uci set network.bat0.multicast_mode='0'
uci commmit network.bat0

uci del network.bat0_hardif_mesh0
uci set network.bat0_hardif_mesh0='interface'
uci set network.bat0_hardif_mesh0.proto='batadv_hardif'
uci set network.bat0_hardif_mesh0.master='bat0'
uci set network.bat0_hardif_mesh0.mtu='1536'
uci commmit network.bat0_hardif_mesh0

exit 0
