#!/bin/sh

. /lib/functions.sh

board=$(board_name)
is_lowcost="`acc hw get Model | awk -F"-" '{print $3}'`"

case $board in
  edgecore,eap104)
    if [ "$is_lowcost" == "L" ]; then
      uci set ibeacon.ibeacon.enabled=0
      uci commit ibeacon.ibeacon
    fi
    ;;
esac

