#!/bin/sh

. /lib/functions.sh

add_fw_ssid_iso(){
	uci -q batch <<-EOF
	delete firewall.ssidiso_inc
	set firewall.ssidiso_inc=include
	set firewall.ssidiso_inc.path='/etc/firewall.ssid_isolation'
	set firewall.ssidiso_inc.reload='1'
	set firewall.ssidiso_inc.type='script'
	EOF
}

add_fw_ssid_iso
uci commit firewall

exit 0
