#!/bin/sh
if [ ! -f /etc/config/users ]; then
> /etc/config/users
uci batch <<-EOF >/dev/null 2>/dev/null
  add users login
  set users.@login[-1].enabled='0'
  set users.@login[-1].name='root'
  set users.@login[-1].passwd='admin123'
  set users.@login[-1].type='admin'
  add users login
  set users.@login[-1].enabled='1'
  set users.@login[-1].name='admin'
  set users.@login[-1].passwd='admin'
  set users.@login[-1].type='admin'
  commit users
EOF
fi
exit 0
