#!/bin/sh

original_log_remote="`uci get system.@system[0].log_remote 2>/dev/null`"

if [ "$original_log_remote" == "" ]; then
        uci set system.@system[0].log_remote='0'
        uci commit system
fi
exit 0
