#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=99

USE_PROCD=1

PROG=/usr/sbin/conntrackd

start_service () {
	local pid=$(pgrep conntrackd)
	if [ "$(uci get system.@system[0].log_conntrackd_enable)" == "1" ]; then
		if [ -z "$pid" ]; then
			procd_open_instance
			procd_set_param command "$PROG" -d
			procd_close_instance
		fi
	else
		if [ -n "$pid" ]; then
			# conntrackd -k may not work when running here (ubus specific?)
			kill $pid
		fi
	fi
}

stop_service () {
	local pid=$(pgrep conntrackd)
	if [ -n "$pid" ]; then
		# conntrackd -k may not work when running here (ubus specific?)
		kill $pid
	fi
}

service_triggers()
{
	procd_add_reload_trigger "system"
}

