#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/sbin/discoveryd

start_service() {
	config_load acn
	config_get discovery_enabled discovery enabled

	[ $discovery_enabled = 0 ] && return 0;

	procd_open_instance
	procd_set_param command "$PROG" -f
	procd_set_param respawn
	procd_close_instance

}

service_triggers() {
	procd_add_reload_trigger "acn"
}
