#!/bin/sh /etc/rc.common

START=98
STOP=40

USE_PROCD=1

PROG=/sbin/ulog-listener

start_service()
{
	# $1: nlgroup number default:3
	# $2: udp port
	# $3: Debug flag  1:debug 2:dump packet others: disable
	procd_open_instance
	procd_set_param command $PROG '3' '12346'
	procd_set_param respawn 3600 1 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}
