#!/bin/sh /etc/rc.common
START=91
USE_PROCD=1

msp_enabled=`uci get acn.settings.msp_enable`

set_user () {
	local enabled
	local name
	local passwd
	local type

	config_get enabled $1 enabled
	config_get name $1 name
	config_get passwd $1 passwd
	config_get type $1 type

	# remove the existing temporary files
	[ -e "/etc/passwd+" ] && rm /etc/passwd+
	[ -e "/etc/shadow+" ] && rm /etc/shadow+

	if [ "$enabled" == "1" ] ; then
		# added group name option
		addgroup -S root 2>/dev/null
		if [ "$msp_enabled" == "1" ]; then
			if [ "$name" == "root" -o "$name" == "admin" ]; then
				adduser -u 0 -h / -H -D -s /bin/ash -G root "$name"
			else
				adduser -u 0 -h / -H -D -s /bin/false -G root "$name"
			fi
		else
			adduser -u 0 -h / -H -D -s /bin/ash -G root "$name"
		fi

		echo "$name:$passwd" | chpasswd -m
	else
		if [ "$name" = "root" ]; then
			# never remove root user, just disable the password
			echo "$name:*" | chpasswd -e
		else
			deluser "$name"
		fi
	fi
}

start_service() {
	[ -e $BIN ] || exit 0

	/sbin/send_clientinfo_period.sh stop 2>/dev/null
	/sbin/channel_balance.sh stop 2>/dev/null
	/sbin/wmi_monitor.sh stop 2>/dev/null
	/sbin/logrotate_cron.sh stop 2>/dev/null
	/sbin/wifi_monitor.sh stop 2>/dev/null
	/etc/init.d/stunnel stop
	/etc/init.d/wifischedule stop

	config_load users

	local root_users=$(cat /etc/passwd | grep "bin/ash"| cut -d ":" -f 0)
	for user_root in $root_users; do
		delgroup $user_root root 2>/dev/null
		deluser "$user_root"
	done
	local all_users=$(cat /etc/passwd | grep "Linux User,,,:/:/bin/false"| cut -d ":" -f 0)

	# local all_users=$(cat /etc/passwd | grep "bin/ash"| cut -d ":" -f 0)
	for user in $all_users; do
		# remove the existing temporary files
		[ -e "/etc/passwd+" ] && rm /etc/passwd+
		[ -e "/etc/shadow+" ] && rm /etc/shadow+

		[ "$user" = "root" ] && continue
		delgroup $user root 2>/dev/null
		deluser "$user"
	done

	config_foreach set_user login
	/sbin/rpcd_add_accout.sh 2>/dev/null
	/sbin/send_clientinfo_period.sh boot 2>/dev/null
	/sbin/channel_balance.sh boot 2>/dev/null
	/sbin/wmi_monitor.sh boot 2>/dev/null
	/sbin/logrotate_cron.sh boot 2>/dev/null
	/sbin/wifi_monitor.sh boot 2>/dev/null
	/etc/init.d/stunnel restart
	if [ "$(uci -q get acn.wizard.ez_setup)" = "0" ]; then
		/etc/init.d/wifischedule restart
	fi
}

service_triggers()
{
	procd_add_reload_trigger users rpcd acn
}

