#!/bin/sh

. /lib/functions.sh

board=$(board_name)
is_lowcost="`acc hw get Model | awk -F"-" '{print $3}'`"

case "$board" in
  edgecore,eap104)
    if [ "$is_lowcost" == "L" ]; then
      uci set ethernet.lan4.poe_out='0'
      uci commit ethernet
    else
      [ -z "$(uci -q get ethernet.lan4.poe_out)" ] && {
        uci set ethernet.lan4.poe_out='1'
        uci commit ethernet
      }
    fi
    ;;
esac

exit 0
