#!/bin/sh

. /lib/functions.sh

board=$(board_name)


update=0

case "$board" in
	edgecore,eap101)
		if [ "$(uci -q show system.led_poe)" != "" ]; then
			uci del system.led_poe
			update=1
		fi
		if [ "$(uci -q show system.led_wan)" == "" ]; then
			uci set system.led_wan=led
			uci set system.led_wan.name='WAN'
			uci set system.led_wan.sysfs='green:wan'
			uci set system.led_wan.trigger='netdev'
			uci set system.led_wan.dev='eth0'
			uci set system.led_wan.mode='tx rx link'
			update=1
		fi
		;;
	edgecore,eap102|\
	edgecore,oap103)
		if [ "$(uci -q get system.led_wan.trigger)" == "" ]; then
			uci set system.led_wan=led
			uci set system.led_wan.name='WAN'
			uci set system.led_wan.sysfs='green:bt'
			uci set system.led_wan.trigger='netdev'
			uci set system.led_wan.dev='eth0'
			uci set system.led_wan.mode='tx rx link'
			update=1
		fi
		if [ "$(uci -q show system.led_poe)" != "" ]; then
			uci del system.led_poe
			update=1
		fi
		if [ "$(uci -q get system.led_wan.sysfs)" != "green:bt" ]; then
			uci set system.led_wan.sysfs='green:bt'
			update=1
		fi
		;;
esac

if [ "$update" = 1 ]; then
	uci commit system
fi

exit 0
