#!/bin/sh

. /lib/functions.sh

remove_empty() {
  section="$1"
  config_get name ${section} name
  if [ "$name" == "" ]; then
    uci -q delete hotspot20.${section}
  fi
}

config_load hotspot20
config_foreach remove_empty profile
uci commit hotspot20

exit 0
