#!/bin/sh

uci set network.bat0.routing_algo='BATMAN_V'
uci set network.bat0.orig_interval='1000'
uci set network.bat0.bridge_loop_avoidance='0'
uci commmit network.bat0

uci set network.bat0_hardif_mesh0.mtu='2304'
uci commmit network.bat0_hardif_mesh0

exit 0
