#!/bin/sh

if [ "$(uci -q get luci.diag)" != "internal" ]; then
	host=""

	if [ -s /etc/os-release ]; then
		. /etc/os-release
		host="${HOME_URL:-${BUG_URL:-$OPENWRT_DEVICE_MANUFACTURER_URL}}"
		host="${host#*://}"
		host="${host%%/*}"
	fi
fi

exit 0
