#!/bin/sh
if [ ! -f /etc/config/telnetd ]; then
> /etc/config/telnetd
uci batch <<-EOF >/dev/null 2>/dev/null
  add telnetd telnetd
  set telnetd.@telnetd[-1]=telnetd
  set telnetd.@telnetd[-1].Port='23'
  set telnetd.@telnetd[-1].enable='1'
  commit telnetd
EOF
fi
exit 0
