#!/bin/sh

trap_enable=$(uci -q get snmpd.snmp_trap.enable)
server_ip=$(uci -q get snmpd.snmp_trap.server_ip)

# linkDown:     snmptrap -v 2c -c public <server_ip> "" 1.3.6.1.6.3.1.1.5.3 1.3.6.1.2.1.2.2.1.1.<X> i <X>
# linkUp:       snmptrap -v 2c -c public <server_ip> "" 1.3.6.1.6.3.1.1.5.4 1.3.6.1.2.1.2.2.1.1.<X> i <X>
# X = interface number (ifIndex) as assigned in 'ip link command'

# send traps only when enabled at /etc/config/snmpd
if [ -n "$trap_enable" ] && [ -n "$server_ip" ]; then
    # linkUp/linkDown
    sleep 5

    check2=
    ip monitor link | while read LINE; do
        if [[ "$LINE" == "*state DOWN" ]]; then
            check1="state DOWN"
        elif [[ "$LINE" == "*state UP*" ]]; then
            check1="state UP"
        fi

        # get ifIndex value
        ifIndex_val=$(echo $LINE | cut -d ":" -f1)

        # do not send traps when the status repeats (check1 shouldn't be equal to check2)
        if [[ "$check1" != "$check2" ]]; then
            if [[ "$check1" == "state DOWN" ]]; then
                check2=$check1
                # linkDown
                snmptrap -v 2c -c public $server_ip "" 1.3.6.1.6.3.1.1.5.3 1.3.6.1.2.1.2.2.1.1.$ifIndex_val i $ifIndex_val
            elif [[ "$check1" == "state UP" ]]; then
                check2=$check1
                #linkUp
                snmptrap -v 2c -c public $server_ip "" 1.3.6.1.6.3.1.1.5.4 1.3.6.1.2.1.2.2.1.1.$ifIndex_val i $ifIndex_val
            fi
        fi
    done
fi
